# Generated by Django 5.1.3 on 2024-11-07 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('hiking_experience', models.TextField(blank=True)),
                ('favorite_trail', models.CharField(blank=True, max_length=255)),
                ('future_goals', models.TextField(blank=True)),
                ('equipment', models.TextField(blank=True)),
                ('advice_for_beginners', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
